/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Crypto",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Crypto__factory>;
    getContractFactory(
      name: "DummyWorldID",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DummyWorldID__factory>;
    getContractFactory(
      name: "IWorldID",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWorldID__factory>;
    getContractFactory(
      name: "ZkTurk",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZkTurk__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Crypto",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Crypto>;
    getContractAt(
      name: "DummyWorldID",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DummyWorldID>;
    getContractAt(
      name: "IWorldID",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWorldID>;
    getContractAt(
      name: "ZkTurk",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZkTurk>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
